### ISSUE TITLE
Color Scheme

### ISSUE THREAD

**Issue by Ryan-Koch** [Code-For-Chicago/ceic_wordpress#15]
Build out initial css variables/values for color scheme found in our  [design wireframes](https://www.figma.com/file/17Gh1QK92kD37EoGi14AZL/CEIC-lofi---A?node-id=0%3A1).

**Comment by LynnetteColombo** [comment]
Swatches
light green 10AC84
dark green 0C4148
orange EC79007
white FFFFFF
