### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by Ryan-Koch** [Code-For-Chicago/ceic_wordpress#16]
Develop initial footer using the styling in our [design wireframe]Modify parent template header to match what we're looking for in the [design](https://www.figma.com/file/17Gh1QK92kD37EoGi14AZL/CEIC-lofi---A?node-id=0%3A1)

Icons for footer influenced by work on: https://github.com/Code-For-Chicago/ceic_wordpress/issues/29

**Comment by Ryan-Koch** [comment]
Would be a good idea to talk to @LynnetteColombo about the social media icons.

**Comment by LynnetteColombo** [comment]
Footer is ready to go for desktop and mobile in the Figma file
