### ISSUE TITLE
Research what will be involved to integrate with mailchimp.

### ISSUE THREAD

**Issue by Ryan-Koch** [Code-For-Chicago/ceic_wordpress#21]
* Looking to be able to add folks to a mailing list

**Comment by kwritenow** [comment]
Ask CEIC for MailChimp API key
Mailchimp has a plugin, so certain fields will be available. https://mailchimp.com/help/connect-or-disconnect-list-subscribe-for-wordpress/

**Comment by LynnetteColombo** [comment]
Asked CEIC for MailChimp API key. I'll follow up with Alex via email
