### ISSUE TITLE
Address accessibility - perform accessibility tests with Google light house and address weak points.

### ISSUE THREAD

**Issue by Ryan-Koch** [Code-For-Chicago/ceic_wordpress#26]
- Determine necessary level of ADA compliance
- Make site logical to screen readers: logical structure, link titles, doesn't require javascript to access content etc.
- Check color contrast: links and labels, for example

**Comment by Ryan-Koch** [comment]
This is largely a question of how much/what level we want to get into as a requirement.

**Comment by DaveyDevs** [comment]
Hey all, just did an accessibility test with Light House and found the following: 

- Got score of 87
	- Background and foreground colors do not have a sufficient contrast ratio.
		- © 2020, Cannabis Equity Illinois Coalition
	- The logo is missing an alt attribute
        - The <a> tag for the logo does not have a "discernible name"

I can look into it more this week and try a fix or two if no one gets to it first. Thanks!
