### ISSUE TITLE
Share button for events/posts

### ISSUE THREAD

**Issue by Ryan-Koch** [Code-For-Chicago/ceic_wordpress#28]
** needs clarification from the coalition before we begin: which content to share? to which sites?

Research plugins to see what's available, which sites are available by default

**Comment by Ryan-Koch** [comment]
@LynnetteColombo is going to put these in places that they think make sense within the [wireframe](https://www.figma.com/file/17Gh1QK92kD37EoGi14AZL/CEIC-lofi---A?node-id=0%3A1)

**Comment by LynnetteColombo** [comment]
https://sharethis.com/platform/share-buttons-wordpress/
this plugin might be useful.

**Comment by MissFerrety** [comment]
It's been largely my experience with social media plugins that they are best avoided if you are doing custom work anyway. They're resource hogs and more often than not have some incredibly annoying feature and/or lack a feature that you'd prefer to have. Most things will have a copy/paste line or block of code that we can utilize in any way we wish with very little effort.
