### ISSUE TITLE
Integrate social media - links to Coalition social media accounts

### ISSUE THREAD

**Issue by Ryan-Koch** [Code-For-Chicago/ceic_wordpress#29]
Add links to: instagram, facebook, twitter
Create icons

uploaded Insta, fb, twitter icons in white

**Comment by LynnetteColombo** [comment]
https://fontawesome.com/icons/facebook-square?style=brands
https://fontawesome.com/icons/instagram?style=brands
https://fontawesome.com/icons/twitter-square?style=brands

Font Awesome icons
