### ISSUE TITLE
Look at responsiveness of site layout and items and make adjustments

### ISSUE THREAD

**Issue by Ryan-Koch** [Code-For-Chicago/ceic_wordpress#40]

**Comment by zzboncak** [comment]
The hamburger menu currently appears on the left next to the logo. To me it seems like it should appear on the right side to balance it out.

<img width="500" alt="Screen Shot 2020-05-26 at 5 26 55 PM" src="https://user-images.githubusercontent.com/42123379/82956604-c3505300-9f76-11ea-9e8e-256908416d24.png">
