### ISSUE TITLE
Research what will be involved to integrate with google calendar

### ISSUE THREAD

**Issue by Irob466** [Code-For-Chicago/ceic_wordpress#7]
**Some** angles to look at this from:
* Is there an API we can call to pull data down and do with it as we choose?
* Alternatively is there an embed we can use? Does this do what we need it to do?
* Is there another path outside those two?

**Comment by christopherowenowens** [comment]
https://support.google.com/calendar/answer/41207?hl=en
Google only has a single share method (URL or iFrame), with default view:
Default calendar example: https://in-tuned.com/cal
(the iframe version of this is the same, but with a width of like, 400, isn't responsive, etc)

Per Ryan, first iteration might just be to put this place, and then look at putting on a plugin / theme / etc later.

**Comment by Irob466** [comment]
Do any of these plugins through Wordpress' [plugin store](https://wordpress.org/plugins/tags/google-calendar/) potentially do what we need with minimal configuration? The top one, [Simple Calendar](https://wordpress.org/plugins/google-calendar-events/), looks like it has themes that may match with the design that we're going with.
